# Generated by Django 5.1.1 on 2024-10-03 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LengthSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(choices=[('en', 'Английский'), ('ar', 'Арабский'), ('hy', 'Армянский'), ('bg', 'Болгарский'), ('hu', 'Венгерский'), ('vi', 'Вьетнамский'), ('el', 'Греческий'), ('da', 'Датский'), ('he', 'Иврит'), ('is', 'Исландский'), ('es', 'Испанский'), ('it', 'Итальянский'), ('zh', 'Китайский'), ('ko', 'Корейский'), ('lv', 'Латышский'), ('lt', 'Литовский'), ('ms', 'Малайский'), ('de', 'Немецкий'), ('nl', 'Нидерландский'), ('no', 'Норвежский'), ('fa', 'Персидский'), ('pl', 'Польский'), ('pt', 'Португальский'), ('ro', 'Румынский'), ('ru', 'Русский'), ('sk', 'Словацкий'), ('sl', 'Словенский'), ('th', 'Тайский'), ('tr', 'Турецкий'), ('uk', 'Украинский'), ('fi', 'Финский'), ('fr', 'Французский'), ('hi', 'Хинди'), ('cs', 'Чешский'), ('sv', 'Шведский'), ('ja', 'Японский')], max_length=30)),
                ('level_skill', models.CharField(choices=[('elementary', 'начальный'), ('Pre-Intermediate', 'ниже среднего'), ('Intermediate', 'средний'), ('Upper-Intermediate', 'выше среднего'), ('Advanced', 'продвинутый'), ('Proficiency', 'профессиональный')], max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
