# Generated by Django 5.1.1 on 2024-10-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LengthSkill',
            new_name='LanguageSkill',
        ),
        migrations.RenameField(
            model_name='languageskill',
            old_name='length',
            new_name='language',
        ),
    ]
