# Generated by Django 5.1.1 on 2024-10-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_languageskill_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languageskill',
            old_name='user_id',
            new_name='user',
        ),
    ]
