LEVEL_SKILL = (
    ("elementary", "начальный"),
    ("Pre-Intermediate", "ниже среднего"),
    ("Intermediate", "средний"),
    ("Upper-Intermediate", "выше среднего"),
    ("Advanced", "продвинутый"),
    ("Proficiency", "профессиональный"),
)

LANGUAGE_LIST = (
    ('en', 'Английский'),
    ('ar', 'Арабский'),
    ('hy', 'Армянский'),
    ('bg', 'Болгарский'),
    ('hu', 'Венгерский'),
    ('vi', 'Вьетнамский'),
    ('el', 'Греческий'),
    ('da', 'Датский'),
    ('he', 'Иврит'),
    ('is', 'Исландский'),
    ('es', 'Испанский'),
    ('it', 'Итальянский'),
    ('zh', 'Китайский'),
    ('ko', 'Корейский'),
    ('lv', 'Латышский'),
    ('lt', 'Литовский'),
    ('ms', 'Малайский'),
    ('de', 'Немецкий'),
    ('nl', 'Нидерландский'),
    ('no', 'Норвежский'),
    ('fa', 'Персидский'),
    ('pl', 'Польский'),
    ('pt', 'Португальский'),
    ('ro', 'Румынский'),
    ('ru', 'Русский'),
    ('sk', 'Словацкий'),
    ('sl', 'Словенский'),
    ('th', 'Тайский'),
    ('tr', 'Турецкий'),
    ('uk', 'Украинский'),
    ('fi', 'Финский'),
    ('fr', 'Французский'),
    ('hi', 'Хинди'),
    ('cs', 'Чешский'),
    ('sv', 'Шведский'),
    ('ja', 'Японский'),
)

MENU = [
    {'title':'Диалог', 'url_name': 'lesson'},
    {'title':'Поиск собеседника', 'url_name': 'ads_list'},
    {'title':'Пользователь', 'url_name': 'user'},
]

ADS = [
    {'name': 'title1', 'language': 'len1', 'skill': 'skill_lvl', 'url_name': 'ads1'},
    {'name': 'title2', 'language': 'len1', 'skill': 'skill_lvl', 'url_name': 'ads2'},
    {'name': 'title3', 'language': 'len1', 'skill': 'skill_lvl', 'url_name': 'ads3'},
    {'name': 'title4', 'language': 'len1', 'skill': 'skill_lvl', 'url_name': 'ads4'},
    {'name': 'title5', 'language': 'len1', 'skill': 'skill_lvl', 'url_name': 'ads5'},
]