version: '3'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - ALLOWED_HOST=192.168.0.9
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6380:6379"