version: 'v2.29.7'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6380:6379"