# Generated by Django 5.1.1 on 2024-10-02 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_to_teach_userA', models.CharField(max_length=30)),
                ('language_to_teach_userB', models.CharField(max_length=30)),
                ('language_to_learn_userA', models.CharField(max_length=30)),
                ('language_to_learn_userB', models.CharField(max_length=30)),
                ('date_lesson', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_userA', to='core.userprofile')),
                ('userB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_userB', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LengthSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(choices=[('en', 'Английский'), ('ar', 'Арабский'), ('hy', 'Армянский'), ('bg', 'Болгарский'), ('hu', 'Венгерский'), ('vi', 'Вьетнамский'), ('el', 'Греческий'), ('da', 'Датский'), ('he', 'Иврит'), ('is', 'Исландский'), ('es', 'Испанский'), ('it', 'Итальянский'), ('zh', 'Китайский'), ('ko', 'Корейский'), ('lv', 'Латышский'), ('lt', 'Литовский'), ('ms', 'Малайский'), ('de', 'Немецкий'), ('nl', 'Нидерландский'), ('no', 'Норвежский'), ('fa', 'Персидский'), ('pl', 'Польский'), ('pt', 'Португальский'), ('ro', 'Румынский'), ('ru', 'Русский'), ('sk', 'Словацкий'), ('sl', 'Словенский'), ('th', 'Тайский'), ('tr', 'Турецкий'), ('uk', 'Украинский'), ('fi', 'Финский'), ('fr', 'Французский'), ('hi', 'Хинди'), ('cs', 'Чешский'), ('sv', 'Шведский'), ('ja', 'Японский')], max_length=30)),
                ('level_skill', models.CharField(choices=[('elementary', 'начальный'), ('Pre-Intermediate', 'ниже среднего'), ('Intermediate', 'средний'), ('Upper-Intermediate', 'выше среднего'), ('Advanced', 'продвинутый'), ('Proficiency', 'профессиональный')], max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_to_learn', models.CharField(choices=[('elementary', 'начальный'), ('Pre-Intermediate', 'ниже среднего'), ('Intermediate', 'средний'), ('Upper-Intermediate', 'выше среднего'), ('Advanced', 'продвинутый'), ('Proficiency', 'профессиональный')], max_length=30)),
                ('length_level_to_learn', models.CharField(choices=[('elementary', 'начальный'), ('Pre-Intermediate', 'ниже среднего'), ('Intermediate', 'средний'), ('Upper-Intermediate', 'выше среднего'), ('Advanced', 'продвинутый'), ('Proficiency', 'профессиональный')], max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
    ]
