# Generated by Django 5.1.1 on 2024-10-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='userA',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='userB',
        ),
        migrations.AddField(
            model_name='lesson',
            name='userA',
            field=models.ManyToManyField(related_name='lessons_as_userA', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='userB',
            field=models.ManyToManyField(related_name='lessons_as_userB', to='core.userprofile'),
        ),
    ]
