# Generated by Django 5.1.1 on 2024-10-03 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_to_learn', models.CharField(choices=[('elementary', 'начальный'), ('Pre-Intermediate', 'ниже среднего'), ('Intermediate', 'средний'), ('Upper-Intermediate', 'выше среднего'), ('Advanced', 'продвинутый'), ('Proficiency', 'профессиональный')], max_length=30)),
                ('length_level_to_learn', models.CharField(choices=[('elementary', 'начальный'), ('Pre-Intermediate', 'ниже среднего'), ('Intermediate', 'средний'), ('Upper-Intermediate', 'выше среднего'), ('Advanced', 'продвинутый'), ('Proficiency', 'профессиональный')], max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
