# Generated by Django 5.1.1 on 2024-10-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_rename_user_id_advertisement_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='slug_id',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
