# Generated by Django 5.1.1 on 2024-10-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_advertisement_slug_id_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='slug_id',
        ),
    ]
