# Generated by Django 5.1.1 on 2024-10-10 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_remove_advertisement_slug_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='language_to_learn',
            field=models.CharField(choices=[('Английский', 'Английский'), ('Арабский', 'Арабский'), ('Армянский', 'Армянский'), ('Армянский', 'Болгарский'), ('Венгерский', 'Венгерский'), ('Вьетнамский', 'Вьетнамский'), ('Греческий', 'Греческий'), ('Датский', 'Датский'), ('Иврит', 'Иврит'), ('Исландский', 'Исландский'), ('Испанский', 'Испанский'), ('Итальянский', 'Итальянский'), ('Китайский', 'Китайский'), ('Корейский', 'Корейский'), ('Латышский', 'Латышский'), ('Литовский', 'Литовский'), ('Малайский', 'Малайский'), ('Немецкий', 'Немецкий'), ('Нидерландский', 'Нидерландский'), ('Норвежский', 'Норвежский'), ('Персидский', 'Персидский'), ('Польский', 'Польский'), ('Португальский', 'Португальский'), ('Румынский', 'Румынский'), ('Русский', 'Русский'), ('Словацкий', 'Словацкий'), ('Словенский', 'Словенский'), ('Тайский', 'Тайский'), ('Турецкий', 'Турецкий'), ('Украинский', 'Украинский'), ('Финский', 'Финский'), ('Французский', 'Французский'), ('Хинди', 'Хинди'), ('Чешский', 'Чешский'), ('Шведский', 'Шведский'), ('Японский', 'Японский')], max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
