# Generated by Django 5.1.1 on 2024-10-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_alter_advertisement_language_to_learn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
    ]
