# Generated by Django 5.1.1 on 2024-10-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0010_notification_unique_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='room',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
