# Generated by Django 5.1.1 on 2024-11-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_notification_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
