# Generated by Django 5.1.1 on 2024-11-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0012_advertisement_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('-data',)},
        ),
    ]
