# Generated by Django 5.1.1 on 2024-10-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_to_teach_userA', models.CharField(max_length=30)),
                ('language_to_teach_userB', models.CharField(max_length=30)),
                ('language_to_learn_userA', models.CharField(max_length=30)),
                ('language_to_learn_userB', models.CharField(max_length=30)),
                ('date_lesson', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('userA', models.ManyToManyField(related_name='lessons_as_userA', to='users.userprofile')),
                ('userB', models.ManyToManyField(related_name='lessons_as_userB', to='users.userprofile')),
            ],
        ),
    ]
