# Generated by Django 5.1.1 on 2024-10-05 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='userA',
            field=models.ManyToManyField(related_name='lessons_as_userA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='userB',
            field=models.ManyToManyField(related_name='lessons_as_userB', to=settings.AUTH_USER_MODEL),
        ),
    ]
